### ISSUE TITLE
Any chance you are still into fixing your module?

### ISSUE THREAD

**Issue by Scardaddy** [hakanmhmd/MMM-Stock#5]
Module has been broken for a while.  Just wondering if you were interested in trying to fix it?

**Comment by hakanmhmd** [comment]
Hi, I fixed the api because yahoo finance was deprecated.
I have pushed the code, however I get clientside error concerning the DOM. I am not really sure of the reason.

If you want to have a look and if you fix it send me a PR.

**Comment by Scardaddy** [comment]
I'll have a look tonight.  Thanks for giving it some attention.

**Comment by Scardaddy** [comment]
You beat me to it.  Thanks for putting in the effort, I know it wasn't
easy.  Quick question about the css.  I am only able to get 4 tickers
showing at once.  How specifically are you supposed to manipulate the css,
if you wanted to say add 10 tickers instead of 4.  Assuming I already have
the tickers implemented in the MM config file.

Thanks again,

**Comment by hakanmhmd** [comment]
0%   {margin-top: 0}
    10%  {margin-top: -30px}
    20%  {margin-top: -60px}
    30%  {margin-top: -90px}
    40%  {margin-top: -120px}
    50%  {margin-top: -150px}
    60%  {margin-top: -180px}
    70%  {margin-top: -210px}
    80%  {margin-top: -240px}
    90%  {margin-top: -270px}
    100% {margin-top: 0}

I think this should do it. If might see parts of the previous ticker from above or below. To fix that play with the line height of each ticker. You could remove the padding too
